### ISSUE TITLE
Refine PerformanceTestCase API

### ISSUE THREAD

**Issue by jsbean** [dn-m/PerformanceTesting#1]

**Comment by mossheim** [comment]
possible improvements to consider:

- [x] change from Strides to [Double]s (more flexible, easier to represent geometric series)
- [x] factor benchmark[Non]MutatingOperation
- [ ] time an inner loop rather than just one iteration of test code (or provide functions to do this)
- [ ] provide a default mock object that is just an empty `C`
- [x] consider using true/false flag for mutating - makes the type of test more explicit than including it in function name
- [ ] provide generic setup functions for filling with ints (like those already found in test files)
- [ ] provide benchmark & assert in single function for convenience
- [x] consider making `debug` settable

**Comment by mossheim** [comment]
also:
- [x] consider renaming "operation" -> "closure"

**Comment by mossheim** [comment]
re "provide a default mock object" - i think this is going to be an uphill battle unless I can find some simpler way to do it. there are a couple protocols that provide default empty constructors - "ExpressibleByArrayLiteral", "RangeReplaceableCollection", "SetAlgebra", etc. In a playground test it took 3 overloads to get it to conform for String, Set, Dictionary, and Array – ExpressibleByDictionaryLiteral (for Dict), RangeReplaceableCollection (for Array, String), SetAlgebra (for Set). I don't know if it's worth it...

**Comment by jsbean** [comment]
You could always import `Algebra`, and use an `Additive` monoid (`.zero`) :).

Which actually brings to mind, in `Algebra`, I don't think we made `[:]` the `.zero` for `Dictionary`.

**Comment by mossheim** [comment]
similar problems for generic setup functions - the only protocols i can find to specialize over don't provide the functions that make setup fastest to implement. so that would be a major performance hit (2x ish)

**Comment by jsbean** [comment]
Ahh, interesting.

**Comment by mossheim** [comment]
haha, well i'm not sure that adds much value for other users. it forces an extra dependency and it would be nicer to have generalization over all types that could be empty-constructed for free.
